version: '3.9'

services:
  api:
    build:
      dockerfile: ./Dockerfile
    volumes:
      
      - media-volume:/code_api/media
      - /tmp/app/mysqld:/run/mysqld
    ports:
      - 8050:8050
    restart: unless-stopped
    container_name: api
    command: python manage.py runserver 0.0.0.0:8050
    env_file:
      - ./.env.development
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    privileged: true
    ports:
      - '8100:80'
    restart: always
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 50M
    depends_on:
      - database

volumes:
  backend:
  media-volume:
  mysql-storage:

