# Generated by Django 4.2.15 on 2024-09-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
