# Generated by Django 4.2.15 on 2024-09-29 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_alter_subject_academic_year_alter_subject_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer', '0003_alter_lecturer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lecturer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectlecturer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject'),
        ),
    ]
