# Generated by Django 4.2.15 on 2024-09-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0002_rename_section_subject_departments'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_full_mark', models.FloatField()),
                ('number_of_work', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.files')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject')),
            ],
        ),
    ]
