# Generated by Django 4.2.15 on 2024-09-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('homework', '0002_alter_homework_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='files.files'),
        ),
    ]
