# Generated by Django 4.2.15 on 2024-09-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=50)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('tests_mark', models.IntegerField(blank=True, null=True)),
                ('attendance_mark', models.IntegerField(blank=True, null=True)),
                ('interviews_mark', models.IntegerField(blank=True, null=True)),
                ('homework_mark', models.IntegerField(blank=True, null=True)),
                ('labs_mark', models.IntegerField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.departments')),
            ],
        ),
    ]
