# Generated by Django 4.2.15 on 2024-09-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='section',
            new_name='departments',
        ),
    ]
