# Generated by Django 4.2.15 on 2024-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_rename_section_subject_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='practical_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
