# Generated by Django 4.2.15 on 2024-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
